language: elixir

before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - curl -sL https://deb.nodesource.com/setup_11.x | sudo -E bash -
  - sudo apt-get update -q
  - sudo apt-get install -y nodejs ethereum
before_script:
  - npm install -g ganache-cli

env:
  - GANACHE_EXECUTABLE=ganache-cli

elixir:
  - '1.7'
otp_release: '21.1'

cache:
  directories:
    - _build
    - deps

script:
  - mix credo --strict
  - mix test