language: elixir
dist: xenial
before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update -q
  - sudo apt-get install -y ethereum
before_script:
  - npm install -g ganache-cli

env:
  global:
    - GANACHE_EXECUTABLE=ganache-cli
    - MIX_ENV=test

elixir:
  - '1.7'
otp_release: '21.1'

cache:
  directories:
    - _build
    - deps

script:
  - mix credo --strict
  - mix test