language: elixir

before_install:
  - sudo add-apt-repository -y ppa:ethereum/ethereum
  - sudo apt-get update -q
  - sudo apt-get install -y nodejs ethereum
before_script:
  - cd priv/presets/ganache-cli && npm install -f --no-package-lock && cd -

elixir:
  - '1.7'
otp_release: '21.1'

cache:
  directories:
    - _build
    - deps

script:
  - mix credo --strict
  - mix test